---
directories:
  - directory: tmp/test01
    owner: root
    group: root
    mode: "0755"

files:
  - file: tmp/testfile01
    owner: root
    group: root
    mode: "0644"
  - file: tmp/testfile02
    owner: root
    group: root
    mode: "0644"
  - file: tmp/test01/testfile02
    owner: root
    group: root
    mode: "0644"
